class AppException(Exception): ...

class AuthenticationError(AppException): ...
class NotFoundError(AppException): ...
class ConflictError(AppException): ...

class InvalidCredentialsError(AuthenticationError): ...
